test change for audio
JustRia/Noteable pull request #12
Opened 2019-02-21 20:12 UTC by JustRia

please merge my test

2019-02-21 20:13 UTC, chang382 approved these changes
:+1: friendo

2019-02-21 20:17 UTC, calebflynn13 requested changes

2019-02-21 20:17 UTC, calebflynn13 commented on test/recordingSpec.js
> +        app.webContents.executeJavaScript('document.getElementById("mic-icon").classList.remove("disabled-button")', true);
Can you link this line with the rest of them with a `.then(function() {...})`

2019-02-22 19:37 UTC, calebflynn13 approved these changes

2019-02-22 19:37 UTC, merged