Downloads
JustRia/Noteable pull request #49
Opened 2019-04-11 18:40 UTC by JustRia

Downloads stuff from the things

2019-04-12 15:58 UTC, calebflynn13 commented on renderSheetMusic.js
> -    var output; // will hold final abcjs format for sheet music
Why did you remove this? Don't we want to initialize variables before we use them?

2019-04-12 16:02 UTC, calebflynn13 commented on renderSheetMusic.js
> +function sheetToPdf() {
I'm not sure where in this function it is, but when I run the program, it tries to print rather than download the pdf. Although I'm still able to download a pdf from the print dialog, I think it would make more sense to use a download dialog similar to the one you use for the MIDI download

2019-04-12 17:49 UTC, JustRia commented on renderSheetMusic.js
> +function sheetToPdf() {
Print to pdf was the example from the link aaron gave that I think might've been the official example? - abcjs doesn't have a builtin for download directly like it does for midi

2019-04-13 17:21 UTC, JustRia commented on renderSheetMusic.js
> -    var output; // will hold final abcjs format for sheet music
Hey Caleb! I'd moved the variable outside of the function to be used as a global and then realized I didn't need it to be without moving it back into the function. Oops! It's added back now. Regardless-- this code will work whether or not you properly initialize the variable (even if it's bad practice). Removing its declaration just made it global rather than local.

2019-04-13 17:22 UTC, JustRia commented on renderSheetMusic.js
> +function sheetToPdf() {
Changed it but I had to use a different package :(

2019-04-14 17:25 UTC, calebflynn13 approved these changes
Looks good! Good work 👍

2019-04-16 14:55 UTC, calebflynn13 requested changes

2019-04-16 14:55 UTC, calebflynn13 commented on progressBar.js
> +    document.getElementById("mic-icon").classList.add("hidden");
This actually isn't the best place to put this. The record button will still be there until the first checkpoint is hit. Instead, we should edit the stopRecording() function in rendering.js to not add it back to the screen in the first place

2019-04-17 17:43 UTC, calebflynn13 approved these changes

2019-04-17 18:37 UTC, merged